updated my yaml files

diff --git a/.github/workflows/deployment-prod.yaml b/.github/workflows/deployment-prod.yaml
--- a/.github/workflows/deployment-prod.yaml
+++ b/.github/workflows/deployment-prod.yaml
@@ -86,15 +86,14 @@ jobs:
             sudo systemctl restart yolo.service
 
             echo "⏱ Waiting for service..."
-            sleep 3
-             if curl -s http://localhost:8080/health | grep -q "ok"; then
-            echo "✅ Health check passed."
-             else
-            echo "❌ Health check failed. Showing logs:"
-            journalctl -u yolo-dev.service -n 30 --no-pager
-            exit 1
-             fi
-
+            sleep 10
+            if curl -s http://localhost:8080/health | grep -q "ok"; then
+              echo "✅ Health check passed."
+            else
+              echo "❌ Health check failed. Showing logs:"
+              journalctl -u yolo.service -n 30 --no-pager
+              exit 1
+            fi
 
             echo "✅ Production YOLO deployment complete."
           EOF
